services:
  postgres:
    image: postgres:17
    container_name: domus-postgres

    environment:
      POSTGRES_USER: domus
      POSTGRES_PASSWORD: domus123
      POSTGRES_DB: domus

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: